#include <stdlib.h>
#include "ftype_module.h"

static struct list_node {
	struct ftype_module *module;
	struct list_node *next;
} *modules;

/* defined in modules.c which is generated by configure */
void img_modules_init();

static int done_init;

int img_register_module(struct ftype_module *mod)
{
	struct list_node *node;

	if(!(node = malloc(sizeof *node))) {
		return -1;
	}

	node->module = mod;
	node->next = modules;
	modules = node;
	return 0;
}

struct ftype_module *img_find_format_module(struct img_io *io)
{
	struct list_node *node;

	if(!done_init) {
		img_modules_init();
		done_init = 1;
	}

	node = modules;
	while(node) {
		if(node->module->check(io) != -1) {
			return node->module;
		}
		node = node->next;
	}
	return 0;
}

struct ftype_module *img_guess_format(const char *fname)
{
	struct list_node *node;
	char *suffix;
	int suffix_len;

	if(!done_init) {
		img_modules_init();
		done_init = 1;
	}

	if(!(suffix = strrchr(fname, '.'))) {
		return 0;	/* no suffix, can't guess ... */
	}
	suffix_len = strlen(suffix);

	node = modules;
	while(node) {
		char *suflist = node->module->suffix;
		char *start, *end;

		while(*suflist) {
			if(!(start = strstr(suflist, suffix))) {
				break;
			}
			end = start + suffix_len;

			if(*end == ':' || *end == 0) {
				return node->module;	/* found it */
			}
			suflist = end;
		}

		node = node->next;
	}
	return 0;
}

struct ftype_module *img_get_module(int idx)
{
	struct list_node *node;

	if(!done_init) {
		img_modules_init();
		done_init = 1;
	}

	node = modules;
	while(node && idx--) {
		node = node->next;
	}
	return node;
}
